Add trailing slash to vendor/tinymce path
With manifest storage, the static() function would think this is a file, and try to find a manifest entry for it.
This resulted in an error:

ValueError: Missing staticfiles manifest entry for 'wagtailtinymce/js/vendor/tinymce'